#!/bin/bash

if [ ! -d "$HOME/.rvm/" ]; then
  bash < <( curl -s https://rvm.beginrescueend.com/releases/rvm-install-head )
fi

if ! grep -q ".rvm/scripts/rvm" ~/.profile; then
  echo '[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"  # This loads RVM into a shell session.' >> ~/.profile
fi

source ~/.profile

if ! grep -q "bundler" ~/.rvm/gemsets/global.gems; then
  echo 'bundler' >> ~/.rvm/gemsets/global.gems
fi

if ! grep -q "gemedit" ~/.rvm/gemsets/global.gems; then
  echo 'gemedit' >> ~/.rvm/gemsets/global.gems
fi

rvm reload

if ! rvm list | grep -q 1.8.7; then
  echo "Installing Ruby 1.8.7"
  rvm install 1.8.7
fi

if ! rvm list | grep -q 1.9.2; then
  echo "Installing Ruby 1.9.2"
  rvm install 1.9.2
fi

