#!/bin/bash

if [ ! -d "~/.rvm/" ]; then
  bash < <( curl http://rvm.beginrescueend.com/releases/rvm-install-head )
fi

if [[ `fgrep '$HOME/.rvm/scripts/rvm' ~/.profile` -ne 0 ]]; then
  echo '[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"  # This loads RVM into a shell session.' >> ~/.profile
fi

if [[ `rvm list | grep -q 1.8.7` -ne 0 ]]; then
  rvm install 1.8.7
fi

if [[ `rvm list | grep -q 1.9.2` -ne 0 ]]; then
  rvm install 1.9.2
fi

rvm --default use 1.9.2@global
gem install bundler

rvm use 1.8.7
gem install bundler
