#!/bin/bash

if [ ! -d "$HOME/.rvm/" ]; then
  bash < <( curl http://rvm.beginrescueend.com/releases/rvm-install-head )
fi

if ! grep -q ".rvm/scripts/rvm" ~/.profile; then
  echo '[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"  # This loads RVM into a shell session.' >> ~/.profile
  source ~/.profile
fi

rvm reload

if ! rvm list | grep -q 1.8.7; then
  echo "Installing Ruby 1.8.7"
  rvm install 1.8.7
fi

if ! rvm list | grep -q 1.9.2; then
  echo "Installing Ruby 1.9.2"
  rvm install 1.9.2
fi

rvm --default use 1.9.2@global
gem install bundler

rvm use 1.8.7@global
gem install bundler
