#!/bin/bash

if [ $(sysctl kern.sysv.shmall | sed s/\[^0-9]*//) -lt 65536 ]; then
  echo "Running 'sudo sysctl -w kern.sysv.shmall=65536'"
  sudo sysctl -w kern.sysv.shmall=65536
  echo "Running 'sudo sed -Ei -- \"s/^kern.sysv.shmall=(.*)$/kern.sysv.shmall=65536\\\\\"$'\n'\"#kern.sysv.shmall=\1/\" /etc/sysctl.conf'"
  sudo sed -Ei -- "s/^kern.sysv.shmall=(.*)$/kern.sysv.shmall=65536\\"$'\n'"#kern.sysv.shmall=\1/" /etc/sysctl.conf
fi

if ! brew list postgresql >& /dev/null; then
  brew install postgresql
  initdb /usr/local/var/postgres
fi

if [ ! -d ~/Library/LaunchAgents ]; then
  mkdir -p ~/Library/LaunchAgents
fi

if [ ! -f ~/Library/LaunchAgents/org.postgresql.postgres.plist ]; then
  cp /usr/local/Cellar/postgresql/9.0.4/org.postgresql.postgres.plist ~/Library/LaunchAgents/
fi

if ! launchctl list | grep -q org.postgresql.postgres; then
  launchctl load -w ~/Library/LaunchAgents/org.postgresql.postgres.plist
fi

