#!/bin/bash

if ! grep -q ".home/.profile" ~/.profile; then
  echo 'source $HOME/.home/.profile' >> ~/.profile
  source ~/.profile
fi

./homebrew/setup
./ack/setup
./nokogiri/setup
./postgresql/setup
#./mysql/setup
#./ruby/setup
