#!/bin/bash

if ! port installed | grep -q p5-app-ack; then
  echo "Running 'sudo port install p5-app-ack'"
  sudo port install p5-app-ack
fi

if [ ! -e "$HOME/.ackrc" ]; then
  ln -s ~/.home/ack/.ackrc ~/.ackrc
fi
