#!/bin/bash

if [ ! -e "/Library/LaunchDaemons/com.mysql.mysqld.plist" ]; then
  echo "Running 'sudo cp ~/.home/mysql/com.mysql.mysqld.plist /Library/LaunchDaemons/'"
  sudo cp ~/.home/mysql/com.mysql.mysqld.plist /Library/LaunchDaemons/
  echo "Running 'sudo chown root:wheel /Library/LaunchDaemons/com.mysql.mysqld.plist'"
  sudo chown root:wheel /Library/LaunchDaemons/com.mysql.mysqld.plist
  echo "Running 'sudo chmod 644 /Library/LaunchDaemons/com.mysql.mysqld.plist'"
  sudo chmod 644 /Library/LaunchDaemons/com.mysql.mysqld.plist
fi

echo "Running 'sudo launchctl list'"
if ! sudo launchctl list | grep -q com.mysql.mysqld; then
  sudo launchctl load /Library/LaunchDaemons/com.mysql.mysqld.plist
fi
